Bugfix/make graffiti valid ida plugin
yoavst/Graffiti pull request #7
Opened 2024-02-21 08:57 UTC by urielmalin

basic refactor graffiti into IDA expected plugin format
please merge after https://github.com/yoavst/Graffiti/pull/6

2024-02-23 11:19 UTC, yoavst requested changes
Can you also modify [the docs](https://github.com/yoavst/Graffiti/blob/master/docs/platforms/IDA.md) with instructions how to install ida plugin?

You can add "installing into user directory" section from [here](https://hex-rays.com/blog/igors-tip-of-the-week-103-sharing-plugins-between-ida-installs/)

(Also apply comments from #6

2024-02-23 11:19 UTC, yoavst commented on backends/ida/graffiti.py
> +    comment = "Add support for CPP navigating on top of ida_kernelcache"
Wrong comment :)
```suggestion
    comment = "Create customized callgraph directly from IDA"
```

2024-02-23 11:19 UTC, yoavst commented on backends/ida/graffiti.py
> +        super().__init__()
idapython2 compatibility:

```suggestion
        super(idaapi.plugin_t, self).__init__()
```

2024-02-25 06:28 UTC, urielmalin commented on backends/ida/graffiti.py
> +    comment = "Add support for CPP navigating on top of ida_kernelcache"
haha

2024-02-25 06:31 UTC, urielmalin commented
Will update docs later, for now just put it here for a reference:

> clone the repository and symlink  ~/.idapro/plugins/ida_kcpp_plugin.py to ida_kcpp_plugin.py

2024-03-04 12:29 UTC, merged